Consolidate StockOrderTest + expand model
JasLieb/super-caisse pull request #2
Opened 2020-12-19 16:18 UTC by JasLieb

2020-12-22 21:47 UTC, mathieupages commented on SuperCaisse.Model/Employee.cs
> +            Details details
Pourquoi avoir besoin du Details pour la caissière et le magasinier ?

2020-12-22 21:47 UTC, mathieupages commented on SuperCaisse.Model/OrderReport.cs
> +        public DateTime OrderDate { get; }
Faut-il pas ajouter une 3ème date, celle du retour en cas de problème  ? comme ça on aurait le suivie

2020-12-22 21:47 UTC, mathieupages commented on SuperCaisse.Model/Employee.cs
> +    public abstract class Employee : Person
Je ne suis pas spécialiste de l'héritage, mais si Employee hérite de Person qui possède une propriété Détails pour le redéclaré dans Employee

2020-12-22 21:47 UTC, mathieupages commented on SuperCaisse.Model/StockOrder.cs
> +        public Provider Provider { get; }
Si j'ai bien compris, quand je fais une commande, j'ai qu'un fournisseur ?

2020-12-23 07:43 UTC, JasLieb commented on SuperCaisse.Model/Employee.cs
> +            Details details
Puisque l'employé est une personne (la classe Person contient elle les détails)

2020-12-23 07:44 UTC, JasLieb commented on SuperCaisse.Model/OrderReport.cs
> +        public DateTime OrderDate { get; }
J'aurais pensé aussi, mais pas écrit dans les specs ! Donc je ne me suis pas penché dessus

2020-12-23 07:45 UTC, JasLieb commented on SuperCaisse.Model/StockOrder.cs
> +        public Provider Provider { get; }
REQ-12 :
"Le magasinier peut sélectionner un fournisseur chez lequel il va passer une commande. En parcourant le catalogue d’un fournisseur, le magasinier ajoute à son panier les articles dont il a besoin."

Donc pour moi une commande == un fournisseur

2020-12-23 07:47 UTC, JasLieb commented on SuperCaisse.Model/Employee.cs
> +    public abstract class Employee : Person
Pas la peine de la redéclarer ! Elle existe en effet dans Person et l'employee peut le transmettre au constructeur parent (avec le mot clef _base_)

2020-12-23 08:44 UTC, mathieupages requested changes

2020-12-23 08:44 UTC, mathieupages commented on SuperCaisse.Model/OrderReport.cs
> +        public DateTime OrderDate { get; }
Potentiellement quelque chose à laquelle on n'a pas pensé

2020-12-23 08:44 UTC, mathieupages commented on SuperCaisse.Model/Employee.cs
> +            Details details
à modifier

2020-12-23 08:44 UTC, mathieupages commented on SuperCaisse.Model/Employee.cs
> +    public abstract class Employee : Person
à modifier

2020-12-23 10:30 UTC, Chataigneau commented on SuperCaisse.Model/OrderReport.cs
> +        public DateTime OrderDate { get; }
On est plus dans l'outil de caisse et stock vaut mieux pas qu'on commence à se pencher sur un outil de gestion d'employés aussi (pas dans la consigne)

2020-12-23 15:11 UTC, JasLieb commented on SuperCaisse.Model/OrderReport.cs
> +        public DateTime OrderDate { get; }
Quel rapport avec le "un outil de gestion d'employés aussi"

2020-12-23 15:22 UTC, JasLieb commented on SuperCaisse.Model/Employee.cs
> +    public abstract class Employee : Person
A modifier comment ?

2020-12-23 17:13 UTC, Chataigneau commented on SuperCaisse.Model/OrderReport.cs
> +        public DateTime OrderDate { get; }
On s'en fout de savoir si un employé rentre de congés/maladie ou quoi donc la 3e date pas utile

2020-12-23 19:36 UTC, mathieupages commented on SuperCaisse.Model/Employee.cs
> +    public abstract class Employee : Person
j'ai commenté trop rapidement désolé

2020-12-23 19:58 UTC, mathieupages commented on SuperCaisse.Model/OrderReport.cs
> +        public DateTime OrderDate { get; }
Pas compris, on parle d'un statuts de commande. Et pour l'instant on a mis qu'une date de création et de livraison. et j'ai émis l'idée de rajouter une date de retour, pour avoir le suivie

2020-12-24 23:27 UTC, merged